blog/urls.py
from django.urls import path
from . import views
from .feeds import LatestPostsFeed

app_name = 'blog'

urlpatterns = [
    path('', views.post_list, name='post_list'),

    # Class Based View urls
    path('', views.PostListView.as_view(), name='post_list'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',
         views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
    path('feed/', LatestPostsFeed(), name='post_feed'),
    path('search/', views.post_search, name='post_search'),

]

django_core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap

# from blog.sitemaps import PostSitemap

# sitemaps = {
#     'posts': PostSitemap,
# }

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('contact.urls')),
    path('', include('dynamic_slider.urls')),
    path('', include('notifications.urls')),
    path('', include('django_form.urls')),
    path('', include('abouts.urls')),
    path('', include('downlaod.urls')),
    path('', include('asynchronous.urls')),
    # path('blog/', include('blog.urls', namespace='blog')),
    # path('sitemap.xml', sitemap, {'sitemaps': sitemaps},
    #      name='django.contrib.sitemaps.views.sitemap'),

]

blog/models.py
# from django.db import models
# from django.utils import timezone
# from django.contrib.auth.models import User
# from django.urls import reverse
# from django.db.models.signals import pre_save
# from blog.utils import blog_unique_slug_generator


# class Category(models.Model):
#     title = models.CharField(max_length=120)
#     slug = models.SlugField(null=True, blank=True, max_length=50)
#     timestamp = models.DateTimeField(auto_now_add=True)
#     update = models.DateTimeField(auto_now=True)

#     def __str__(self):
#         return self.title

#     class Meta:
#         ordering = ['-timestamp']


# def category_pre_save_receiver(sender, instance, *args, **kwargs):
#     if not instance.slug:
#         instance.slug = blog_unique_slug_generator(instance)


# pre_save.connect(category_pre_save_receiver, sender=Category)


# class BlogManager(models.Manager):
#     def get_queryset(self):
#         return super(BlogManager, self).get_queryset() \
#             .filter(status='published')


# class Blog(models.Model):
#     STATUS_CHOICES = (
#         ('draft', 'Draft'),
#         ('published', 'Published'),
#     )
#     title = models.CharField(max_length=250)
#     slug = models.SlugField(max_length=250, unique_for_date='publish')
#     author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='blog_posts')
#     category = models.ForeignKey(Category, on_delete=models.CASCADE)
#     body = models.TextField()
#     image = models.FileField(upload_to="blog", blank=True, null=True)
#     description = models.TextField(blank=True, null=True)
#     publish = models.DateTimeField(default=timezone.now)
#     created = models.DateTimeField(auto_now_add=True)
#     updated = models.DateTimeField(auto_now=True)
#     status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='draft')

#     objects = models.Manager()  # The default manager.
#     published = BlogManager()  # Our custom manager.

#     def get_absolute_url(self):
#         return reverse(
#             'blog:post_detail',
#             args=[
#                 self.publish.year,
#                 self.publish.month,
#                 self.publish.day, self.slug
#             ])

#     class Meta:
#         ordering = ('-publish',)

#     def __str__(self):
#         return self.title


# # def blog_pre_save_receiver(sender, instance, *args, **kwargs):
# #     if not instance.slug:
# #         instance.slug = blog_unique_slug_generator(instance)
# #
# #
# # pre_save.connect(blog_pre_save_receiver, sender=Blog)


# class Comment(models.Model):
#     post = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')
#     name = models.CharField(max_length=80)
#     email = models.EmailField(blank=True, null=True)
#     body = models.TextField()
#     created_on = models.DateTimeField(auto_now_add=True)
#     approve = models.BooleanField(default=False)

#     class Meta:
#         ordering = ['created_on']

#     def __str__(self):
#         return 'Comment {} by {}'.format(self.body, self.name)


# class Reply(models.Model):
#     comment = models.ForeignKey(Comment, on_delete=models.CASCADE, related_name='replies')
#     name = models.CharField(max_length=80)
#     body = models.TextField()
#     created_on = models.DateTimeField(auto_now_add=True)
#     approve = models.BooleanField(default=False)

#     class Meta:
#         ordering = ['created_on']

#     def __str__(self):
#         return 'Reply {} by {}'.format(self.body, self.name)

blog/forms.py
from django import forms
from django.forms import Textarea
from .models import Blog, Category, Comment, Reply


class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = [
            'title',
        ]


class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = [
            'title',
            'category',
            'image',
            'description',
        ]


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'email', 'body', 'approve']

        # Override the Customer some fields
        widgets = {
            'body': Textarea(attrs={'rows': 3, 'cols': 3}),
        }


class ReplyForm(forms.ModelForm):
    class Meta:
        model = Reply
        fields = ['name', 'body']

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Blog
from django.views.generic import ListView
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from .forms import EmailPostForm
from django.core.mail import send_mail
from .models import Post, Comment
from .forms import EmailPostForm, CommentForm, SearchForm
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank


def post_list(request):
    object_list = Blog.published.all()
    paginator = Paginator(object_list, 3)  # 3 posts in each page
    page = request.GET.get('page')
    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer deliver the first page
        posts = paginator.page(1)
    except EmptyPage:
        # If page is out of range deliver last page of results
        posts = paginator.page(paginator.num_pages)
    return render(request, 'blog/post/list.html', {'page': page, 'posts': posts})


class PostListView(ListView):
    queryset = Blog.published.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, status='published', publish__year=year, publish__month=month,
                             publish__day=day)
    # List of active comments for this post
    comments = post.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    context = {
        'post': post,
        'comments': comments,
        'new_comment': new_comment,
        'comment_form': comment_form
    }

    return render(request, 'blog/post/detail.html', context)


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri(
                post.get_absolute_url())
            subject = f"{cd['name']} recommends you read " \
                      f"{post.title}"
            message = f"Read {post.title} at {post_url}\n\n" \
                      f"{cd['name']}\'s comments: {cd['comments']}"
            send_mail(subject, message, 'admin@myblog.com',
                      [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
        context = {
            'post': post,
            'form': form,
            'sent': sent
        }
        return render(request, 'blog/post/share.html', context)


def post_search(request):
    form = SearchForm()
    query = None
    search_vector = SearchVector('title', 'body')
    search_query = SearchQuery(query)
    results = Post.published.annotate(
        search=search_vector,
        rank=SearchRank(search_vector, search_query)
    ).filter(search=search_query).order_by('-rank')
    context = {
        'form': form,
        'query': query,
        'results': results
    }
    return render(request, 'blog/post/search.html', context)

blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}
{% block title %}{{ post.title }}{% endblock %}

{% block content %}

    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>

    {{ post.body|linebreaks }}

    <p>
        <a href="{% url "blog:post_share" post.id %}">
            Share this post
        </a>
    </p>

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}

    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}

    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form method="post">
            {{ comment_form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </li>
    {% endfor %}
</ul>

blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
{% block title %}My Blog{% endblock %}
{% block content %}
    <h1>My Blog</h1>
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>
        <p class="date">
            Published {{ post.publish }} by {{ post.author }}
        </p>
        {{ post.body|truncatewords:30|linebreaks }}
    {% endfor %}

    {% include "pagination.htmp" with page=posts %}

{% endblock %}

blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% load blog_tags %}
{% block title %}Search{% endblock %}

{% block content %}

    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>
        {% for post in results %}
            <h4><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></
            h4>
            {{ post.body|markdown|truncatewords_html:5 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
        <p><a href="{% url "blog:post_search" %}">Search again</a></p>
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}

{% endblock %}

blog/templates/blog/post/share.html
{% extends "blog/base.html" %}
{% block title %}Share a post{% endblock %}
{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>"{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.</p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% for field in form %}
                <div>
                    {{ field.errors }}
                    {{ field.label_tag }} {{ field }}
                </div>
            {% endfor %}
            {% csrf_token %}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}